name: teatro_digital
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  sqflite_common_ffi_web: any
  csv: ^5.0.2
  flutter:
    sdk: flutter
  sqflite: ^2.2.0+3
  path: ^1.8.0
  path_provider: ^2.1.1
  web_socket_channel: ^2.4.0
  logger: ^2.0.2+1
  permission_handler: ^11.0.1
  file_picker: ^6.0.0
dev_dependencies:
  drift: ^2.11.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true